# Generated by Django 3.2.25 on 2024-04-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issuebonuspoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebonuspoint',
            old_name='bonus_points',
            new_name='point',
        ),
    ]
