# Generated by Django 3.2.25 on 2024-04-10 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='market_items/')),
            ],
            options={
                'verbose_name': 'Market Item',
                'verbose_name_plural': 'Market Items',
                'db_table': 'MarketItem',
            },
        ),
        migrations.CreateModel(
            name='MarketItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Item Order',
                'verbose_name_plural': 'Market Item Orders',
                'db_table': 'MarketItemOrder',
            },
        ),
    ]
